### ISSUE TITLE
Not install in linux system

### ISSUE THREAD

**Issue by braravind** [dagcoin/devnet#1]
Hello,
      I am installing devnet to my linex system.Its not installing .I have download code from devnet and run given commands in Dockerfile one by one. starting all commands run successfully but 

"npm run blackbytes" this command not run properly.following error showing  in terminal .
Error:  
"/root/devnet/node_modules/byteballcore/main_chain.js:82
throw Error("unstable unit not found: "+best_parent_unit); "

Please check this error and help me to installing this code. What i miss or go to wrong  in this installing process. plz help

Thank You!
Aravind

**Comment by fishera123** [comment]
@braravind Hi, have you tried to run though docker?

**Comment by braravind** [comment]
@fishera123  Yes, we i have run commands though given Dockerfile .

**Comment by braravind** [comment]
@fishera123 Hi,
following all command run successfully.
RUN	npm install
RUN	npm run init
RUN	echo | npm run genesis

But when i run
 "npm run blackbytes" this command it not running give the following  Error.

/root/devnet/node_modules/byteballcore/main_chain.js:82
throw Error ("unstable unit not found: "+best_parent_unit) ;

Error: unstable unit not found: N9KEYxaPA+dXoB6HiE8bwmgKnF7Rub03FEFymYR2l0c=
at /root/devnet/node_modules/byteballcore/main_chain.js:82:12
at /root/devnet/node_modules/byteballcore/storage.js:716:4
at Statement.<anonymous> (/root/devnet/node_modules/byteballcore/sqlite_pool.js:113:6)

Thank You!

**Comment by braravind** [comment]
Hello

I am waiting your response.Please suggest me for set DEVNET on linux system successfully.

Thank You

**Comment by fishera123** [comment]
Hi, dagcoin devnet is not yet finished it is still under development. Now regarding your problem, it says that previous units arent confirmed yet. Are you running explorer when you try to define blackbytes asset?

**Comment by fishera123** [comment]
For faster setup I would suggest to use our prebuilt docker container.

**Comment by braravind** [comment]
Hello fishera123
thanks for reply
i want to forking this dagcoin to make new currency  like we did forking other currencies like litecoin altcoin etc.
for what step i have to do using this because my client to use this so please how to setup all the thing 
to make new coin forking this.
like to make genesis block  means first block   to start a main chain so it can conflict with main dagcoin
its working as seprate new coin  please guide me to do this. 
what steps i have to do and where to change. ..

**Comment by fishera123** [comment]
@braravind if you are looking for defining genesis unit and start your own coin then Dagcoin is not the right project for you. Dagcoin is token defined on top of the byteball platform.

**Comment by fishera123** [comment]
I suggest you look into Byteball. here is the link -> https://github.com/byteball/

**Comment by braravind** [comment]
i not meant to block chain i mean to say that if i forking to atlcoin then i have to make first block (genesis block) to start new coin chain similarly in dag coin there is also main what would i call  block or ball or unit 
not khnow what is name because in block chain we say  first bloc then in dag coin would i say frist part of 
graph  and how to make that  u suggest  byteball dag coin aslo made using byteball 
there is no issue what i make token or coin my questtion is how do i start as saprate  called my coin or toekn  i hope u understand my concern

**Comment by fishera123** [comment]
as I understand you want to register token like it is done in Dagcoin. So I suggest looking at byteball whitepaper and register coin according to that. Here is explained how you can create assets in byteball platform ->> https://byteball.org/Byteball.pdf

**Comment by braravind** [comment]
Hello

I download byteball zip from https://github.com/byteball/byteballcore.git and make database connection
on conf.js file.And i use mysql.but after that what i do? How can check byteball run or not.
Please suggest me which command run on next for run byteball?


Thanks

**Comment by fishera123** [comment]
please, ask this questions in byteball slack tech channel I am sure they will suggest you something. This is not related to dagcoin. Thanks

**Comment by xebi14** [comment]
npm ERR! Error: Not found : devnet-hub 
i am getting this error not able to proceed to even step 2
