### ISSUE TITLE
Problem trying to run devnet

### ISSUE THREAD

**Issue by lsosa3** [dagcoin/devnet#3]
Hi, i am trying to run the devnet with Docker but am getting this error

/root/node_modules/headless-byteball/node_modules/byteballcore/enforce_singleton.js:5
	throw Error("Looks like you are loading multiple copies of byteballcore, which is not supported.\nRunnung 'npm dedupe' might help.");
	^

Error: Looks like you are loading multiple copies of byteballcore, which is not supported.
Runnung 'npm dedupe' might help.
    at Object.<anonymous> (/root/node_modules/headless-byteball/node_modules/byteballcore/enforce_singleton.js:5:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node_modules/headless-byteball/node_modules/byteballcore/conf.js:3:1)
    at Module._compile (module.js:624:30)
npm info lifecycle devnet-witness@1.0.0~genesis: Failed to exec genesis script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devnet-witness@1.0.0 genesis: `node genesis.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devnet-witness@1.0.0 genesis script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T02_57_46_745Z-debug.log
npm info lifecycle devnet@1.0.0~genesis: Failed to exec genesis script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devnet@1.0.0 genesis: `npm --prefix witness run genesis`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devnet@1.0.0 genesis script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T02_57_46_768Z-debug.log
The command '/bin/sh -c echo | npm run genesis' returned a non-zero code: 1

-------------------------

Any ideas what it may be_

**Comment by fishera123** [comment]
hi usually this error means that other pars of the project(hub, witness) is running different versions of byteballcore. Make sure that you use same versions

**Comment by lsosa3** [comment]
Ok, how do i check that?
